//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NatMarchand.SampleIdentityServer.WebApp.Repositories {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NatMarchand.SampleIdentityServer.WebApp.Repositories.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT u.[Id] AS [Subject], u.[Login], p.*
        ///FROM [dbo].[InternalUsers] u
        ///JOIN [dbo].[Profiles] p ON u.[ProfileId] = p.[Id]
        ///WHERE u.[Login] = @Login AND HASHBYTES(&apos;SHA2_256&apos;, CAST((u.[Salt] + @Password) AS VARCHAR)) = u.[HashedPassword].
        /// </summary>
        internal static string CheckUserPassword {
            get {
                return ResourceManager.GetString("CheckUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM [dbo].[Clients] WHERE [ClientId] = @ClientId.
        /// </summary>
        internal static string GetClientByClientId {
            get {
                return ResourceManager.GetString("GetClientByClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT u.[Id] AS Subject, u.[Login], p.* FROM [dbo].[InternalUsers] u JOIN [dbo].[Profiles] p ON u.[ProfileId] = p.[Id] WHERE u.[Id] = @Subject.
        /// </summary>
        internal static string GetInternalUserProfileBySubject {
            get {
                return ResourceManager.GetString("GetInternalUserProfileBySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM [dbo].[ClientRedirectUris] WHERE [ClientId] = @ClientId.
        /// </summary>
        internal static string GetRedirectUrisForClient {
            get {
                return ResourceManager.GetString("GetRedirectUrisForClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM [dbo].[ClientScopes] WHERE [ClientId] = @ClientId.
        /// </summary>
        internal static string GetScopesForClient {
            get {
                return ResourceManager.GetString("GetScopesForClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM [dbo].[ClientSecrets] WHERE [ClientId] = @ClientId.
        /// </summary>
        internal static string GetSecretsForClient {
            get {
                return ResourceManager.GetString("GetSecretsForClient", resourceCulture);
            }
        }
    }
}
